// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGe6ZBlbm5qwFjXwRGCZfkmRjhcV0ckA',
    appId: '1:812912548735:web:a1d98762fbc5d76809184a',
    messagingSenderId: '812912548735',
    projectId: 'partsmart-237c7',
    authDomain: 'partsmart-237c7.firebaseapp.com',
    storageBucket: 'partsmart-237c7.firebasestorage.app',
    measurementId: 'G-BN9PJXBFBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6iRe9h1DI-KEFfpDaVZgkGRxS62iOSCI',
    appId: '1:812912548735:android:116481d4bfeb174609184a',
    messagingSenderId: '812912548735',
    projectId: 'partsmart-237c7',
    storageBucket: 'partsmart-237c7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNGe6ZBlbm5qwFjXwRGCZfkmRjhcV0ckA',
    appId: '1:812912548735:web:b6b176f785c02d6f09184a',
    messagingSenderId: '812912548735',
    projectId: 'partsmart-237c7',
    authDomain: 'partsmart-237c7.firebaseapp.com',
    storageBucket: 'partsmart-237c7.firebasestorage.app',
    measurementId: 'G-446S1FH2NW',
  );
}
